import pytest

from src.player_hand import PlayerHand
from tests.tests_config import (
    ACE_OF_SPADES,
    EIGHT_OF_SPADES,
    FIVE_OF_DIAMONDS,
    FIVE_OF_SPADES,
    FOUR_OF_SPADES,
    JACK_OF_SPADES,
    KING_OF_SPADES,
    NINE_OF_SPADES,
    QUEEN_OF_SPADES,
    SEVEN_OF_SPADES,
    SIX_OF_SPADES,
    TEN_OF_SPADES,
    THREE_OF_SPADES,
    TWO_OF_SPADES,
)

STRAIGHT_FLUSH_LOW = [
    TWO_OF_SPADES,
    THREE_OF_SPADES,
    FOUR_OF_SPADES,
    FIVE_OF_SPADES,
    NINE_OF_SPADES,
    TEN_OF_SPADES,
    ACE_OF_SPADES,
]

STRAIGHT_FLUSH_MED = [
    TWO_OF_SPADES,
    FIVE_OF_SPADES,
    SIX_OF_SPADES,
    SEVEN_OF_SPADES,
    EIGHT_OF_SPADES,
    NINE_OF_SPADES,
    ACE_OF_SPADES,
]

STRAIGHT_FLUSH_HIGH = [
    TWO_OF_SPADES,
    THREE_OF_SPADES,
    TEN_OF_SPADES,
    JACK_OF_SPADES,
    QUEEN_OF_SPADES,
    KING_OF_SPADES,
    ACE_OF_SPADES,
]

STRAIGHT_NO_FLUSH = [
    TWO_OF_SPADES,
    THREE_OF_SPADES,
    FOUR_OF_SPADES,
    FIVE_OF_DIAMONDS,
    NINE_OF_SPADES,
    TEN_OF_SPADES,
    ACE_OF_SPADES,
]

FLUSH_NO_STRAIGHT = [
    TWO_OF_SPADES,
    THREE_OF_SPADES,
    FOUR_OF_SPADES,
    FIVE_OF_SPADES,
    SEVEN_OF_SPADES,
    EIGHT_OF_SPADES,
    NINE_OF_SPADES,
]

NO_FLUSH_NOR_STRAIGHT = [
    TWO_OF_SPADES,
    THREE_OF_SPADES,
    FOUR_OF_SPADES,
    FIVE_OF_DIAMONDS,
    SEVEN_OF_SPADES,
    EIGHT_OF_SPADES,
    NINE_OF_SPADES,
]


def test_validate_straight_flush():
    assert PlayerHand(STRAIGHT_FLUSH_LOW)
    assert PlayerHand(STRAIGHT_FLUSH_MED)
    assert PlayerHand(STRAIGHT_FLUSH_HIGH)
    with pytest.raises(ValueError):
        PlayerHand(STRAIGHT_NO_FLUSH)
    with pytest.raises(ValueError):
        PlayerHand(FLUSH_NO_STRAIGHT)
    with pytest.raises(ValueError):
        PlayerHand(NO_FLUSH_NOR_STRAIGHT)
