import numpy as np

VALUE_OF_POCKET_ACES_BEFORE_SHRINKING = 150
VALUE_OF_WEAKEST_HAND_STILL_IN_TOP_50PCT_OF_HANDS_BEFORE_SHRINKING = 37

MAX_HAND_VALUE_BEFORE_CONVERTING_TO_EXPECTED_VALUE = 200
PRESUMED_PROB_FOR_ACES_TO_WIN_HEADS_UP = 0.85
PRESUMED_PROB_FOR_WEAKEST_HAND_STILL_IN_TOP_50PCT_TO_WIN_HEADS_UP = 0.5

# 100
HAND_VALUE_BONUS_FOR_HEADS_UP_BEFORE_CONVERTING_TO_EXPECTED_VALUE = 50 * 2

# 200 * 0.85 = 170
HAND_VALUE_FOR_ACES_BEFORE_CONVERTING_TO_EXPECTED_VALUE = (
    MAX_HAND_VALUE_BEFORE_CONVERTING_TO_EXPECTED_VALUE
    * PRESUMED_PROB_FOR_ACES_TO_WIN_HEADS_UP
)

# 200 * 0.5 = 100
HAND_VALUE_FOR_WEAKEST_HAND_STILL_IN_TOP_50PCT_BEFORE_CONVERTING_TO_EXPECTED_VALUE = (
    MAX_HAND_VALUE_BEFORE_CONVERTING_TO_EXPECTED_VALUE
    * PRESUMED_PROB_FOR_WEAKEST_HAND_STILL_IN_TOP_50PCT_TO_WIN_HEADS_UP
)


# 170 - 100 = 70
ADJUSTED_VALUE_FOR_ACES_BEFORE_ADDING_FOR_PLAYER_COUNT = (
    HAND_VALUE_FOR_ACES_BEFORE_CONVERTING_TO_EXPECTED_VALUE
    - HAND_VALUE_BONUS_FOR_HEADS_UP_BEFORE_CONVERTING_TO_EXPECTED_VALUE
)

# 100 - 100 = 0
ADJUSTED_VALUE_FOR_WEAKEST_HAND_STILL_IN_TOP_50PCT_BEFORE_ADDING_FOR_PLAYER_COUNT = (
    HAND_VALUE_FOR_WEAKEST_HAND_STILL_IN_TOP_50PCT_BEFORE_CONVERTING_TO_EXPECTED_VALUE
    - HAND_VALUE_BONUS_FOR_HEADS_UP_BEFORE_CONVERTING_TO_EXPECTED_VALUE
)

# 150 - 37 = 113
RANGE_OF_TOP_50PCT_OF_HANDS_BEFORE_SHRINKING = (
    VALUE_OF_POCKET_ACES_BEFORE_SHRINKING
    - VALUE_OF_WEAKEST_HAND_STILL_IN_TOP_50PCT_OF_HANDS_BEFORE_SHRINKING
)

# 70 / 113 = 0.619469
HAND_SHRINK_FACTOR = (
    ADJUSTED_VALUE_FOR_ACES_BEFORE_ADDING_FOR_PLAYER_COUNT
    / RANGE_OF_TOP_50PCT_OF_HANDS_BEFORE_SHRINKING
)

# 150 * 0.619469 = 92L
SHRUNK_VALUE_OF_ACES = np.floor(
    VALUE_OF_POCKET_ACES_BEFORE_SHRINKING * HAND_SHRINK_FACTOR
)

# 37L * 0.619469 = 22L
SHRUNK_VALUE_OF_WEAKEST_HAND_STILL_IN_TOP_50PCT = np.floor(
    VALUE_OF_WEAKEST_HAND_STILL_IN_TOP_50PCT_OF_HANDS_BEFORE_SHRINKING
    * HAND_SHRINK_FACTOR
)

# 92L - 70L = 22L
SUBTRACTION_CONSTANT_AFTER_SHRINKING = (
    SHRUNK_VALUE_OF_ACES - ADJUSTED_VALUE_FOR_ACES_BEFORE_ADDING_FOR_PLAYER_COUNT
)

# 22L - 0L = 22L
OTHER_SUBTRACTION_CONSTANT_AFTER_SHRINKING = (
    SHRUNK_VALUE_OF_WEAKEST_HAND_STILL_IN_TOP_50PCT
    - ADJUSTED_VALUE_FOR_WEAKEST_HAND_STILL_IN_TOP_50PCT_BEFORE_ADDING_FOR_PLAYER_COUNT
)
